stalker_api_arme:
    type: rest
    resource: "StalkerBundle\\Controller\\ArmeController"
    prefix: /arme

stalker_api_utilisateur:
    type: rest
    resource: "StalkerBundle\\Controller\\UtilisateurController"
    prefix: /utilisateur