stalker_api_user:
    type: rest
    resource: "StalkerBundle/Controller/UserController"
    #prefix: /user

stalker_api_arme:
    type: rest
    resource: "StalkerBundle/Controller/ArmeController"
    #prefix: /user

#alptis_chronos_api_entites:
    #type: rest
    #resource: "Alptis\Chronos\ApiBundle\Controller\EntitesController"