#stalker:
    #resource: "@StalkerBundle/Controller/"
    #type: annotation
    #prefix: /

#fos_user:
    #resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#app:
    #resource: "@AppBundle/Controller/"
    #type: annotation

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix: /api/doc


stalker_api:
    type: rest
    resource: "@StalkerBundle/Resources/config/routing.yml"
    prefix: /stalker

#stalker:
    #resource: "@StalkerBundle/Controller/"
    #type: annotation
    #prefix: /





#users:
    #type: rest
    #prefix: /

#users:
    #resource: StalkerBundle\Controller\UserController
    #type: rest
