<?php

namespace StalkerBundle\Repository;

/**
 * ArmeMunitionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArmeMunitionRepository extends \Doctrine\ORM\EntityRepository
{
}
